// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 Milos Vasic

// Package llm defines the LLM agent interface and prompt templates for
// documentation processing. The LLMAgent interface is injected by the caller,
// keeping this module decoupled from any specific LLM orchestrator.
package llm

import (
	"context"
)

// RawFeature is an unprocessed feature extracted by the LLM.
type RawFeature struct {
	Name        string `json:"name"`
	Description string `json:"description"`
	Category    string `json:"category"`
	Platforms   []string `json:"platforms"`
	Priority    string `json:"priority"`
}

// FeatureCategory is re-declared here as a string to avoid circular imports.
// The feature package maps from this to its own FeatureCategory type.
type FeatureCategory string

// Feature is a minimal feature representation for LLM interactions.
// The full Feature type lives in the feature package.
type Feature struct {
	ID          string
	Name        string
	Description string
	Category    string
	Platforms   []string
}

// ExpectedScreen is a screen inferred by the LLM.
type ExpectedScreen struct {
	ID          string   `json:"id"`
	Name        string   `json:"name"`
	Description string   `json:"description"`
	Features    []string `json:"features"`
	Platforms   []string `json:"platforms"`
}

// TestStep is a test step generated by the LLM.
type TestStep struct {
	Order       int    `json:"order"`
	Action      string `json:"action"`
	Expected    string `json:"expected"`
	ScreenID    string `json:"screen_id"`
	Platform    string `json:"platform"`
	Description string `json:"description"`
}

// LLMAgent defines the interface for LLM-powered documentation processing.
// Implementations are injected by the caller (e.g., HelixQA bridges
// LLMOrchestrator's Agent to this interface via an adapter).
type LLMAgent interface {
	// Summarize produces a concise summary of the given text.
	Summarize(ctx context.Context, text string) (string, error)

	// ExtractFeatures extracts raw features from documentation text.
	ExtractFeatures(ctx context.Context, text string) ([]RawFeature, error)

	// ClassifyFeature assigns a category to a raw feature.
	ClassifyFeature(ctx context.Context, feature RawFeature) (FeatureCategory, error)

	// InferScreens infers expected application screens from features.
	InferScreens(ctx context.Context, features []Feature) ([]ExpectedScreen, error)

	// GenerateTestSteps generates verification steps for a feature.
	GenerateTestSteps(ctx context.Context, feature Feature) ([]TestStep, error)
}
